### ISSUE TITLE
Possibly returning null from getBox

### ISSUE THREAD

**Issue by migueloller** [alexreardon/css-box-model#8]
Hi Alex!

Thanks for making this library! Super helpful for all things DOM layout.

There's a pesky issue when measuring an element that has `display: none`. `getComputedStyle` will return the [used values](https://developer.mozilla.org/en-US/docs/Web/CSS/used_value) if the element has `display: none` and the [computed values](https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value) otherwise. What this means is that calling `getBox` on an element with `display: none` will result in an error as the used values could be a length (e.g., `em`, `rem`, etc.) or a keyword like `auto`.

Would you be open to making the signature of `getBox` `(el: Element) => ?BoxModel`? I thought of just wrapping the method in a try/catch in our codebase but we measure layout a large amount of times and a try/catch block would slow it down a lot.

There's more info on the quirks of `getComputedStyle`'s resolved values [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#Notes).

If this is something you're open to, I'd happily open a PR.

**Comment by alexreardon** [comment]
Interesting! Perhaps if it is `display:none` we return `0` for all values?

**Comment by migueloller** [comment]
That's a possibility. I do wonder if that's the only case and is the "correct" source of truth for something link this. I tried finding an exhaustive list of what would cause this but had no luck finding one. Perhaps more research is required, or a dive into the spec.

If `display: none` is the only case for this, returning `0` for all values would definitely work, though!

**Comment by alexreardon** [comment]
I think returning `0` when we detect that there is no `px` prefix is a reasonable way forward
